import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import SessionProviders from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Coffee Terios & Toast',
    description: 'Generated by create next app',
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProviders>
                    <AntdRegistry>{children}</AntdRegistry>
                </SessionProviders>
            </body>
        </html>
    );
}
